# Codecov configuration for tomat
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "benches/**/*"
  - "examples/**/*"
