version: "3"

tasks:
  lint:
    desc: Run linter
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  build-release:
    desc: Build release version
    cmds:
      - cargo build --release

  test-debug:
    desc: Run tests with debug logging
    cmds:
      - RUST_LOG=debug cargo test

  test-quiet:
    desc: Run tests quietly (no debug output)
    cmds:
      - RUST_LOG=off cargo test

  coverage:
    desc: Generate code coverage report
    cmds:
      - cargo llvm-cov --all-features --workspace --html
      - echo "Coverage report generated at target/llvm-cov/html/index.html"

  coverage-open:
    desc: Generate and open coverage report in browser
    cmds:
      - cargo llvm-cov --all-features --workspace --open

  dev:
    desc: Development workflow - check, test, lint
    cmds:
      - cargo check
      - cargo test
      - cargo clippy --all-targets --all-features -- -D warnings
